"""Temporary rewrite of the legacy retry test that encoded implicit provider failover."""
from pathlib import Path

path = Path("backend/tests/test_universal_lifecycle.py")
text = path.read_text()
old = '''@pytest.mark.asyncio\nasync def test_provider_can_change_between_attempts_without_changing_transfer(core):\n    error = failure(Category.PROVIDER_UNAVAILABLE, retryability=Retryability.BACKOFF, recovery=Recovery.BACKOFF)\n    core.provider.responses = [ResolutionResult(ResourceState.UNKNOWN, error=error)]\n    transfer = await submit(core)\n    await core.engine.tick()\n    alternate = ParcelProvider("other-parcel")\n    core.registry.register_provider(alternate)\n    core.registry.mark_health(core.provider.descriptor.id, healthy=False)\n    core.now[0] += 1\n    await core.engine.tick()\n    assert (await core.repository.get(transfer.id)).state == TransferState.TRANSFERRING\n    async with database.get_db() as db:\n        attempts = await db.fetchall("SELECT provider_id FROM resolution_attempts ORDER BY rowid")\n    assert [row["provider_id"] for row in attempts] == ["parcel-lab", "other-parcel"]\n    assert len(await core.repository.active()) == 1\n'''
new = '''@pytest.mark.asyncio\nasync def test_provider_retry_stays_bound_to_original_route(core):\n    error = failure(Category.PROVIDER_UNAVAILABLE, retryability=Retryability.BACKOFF, recovery=Recovery.BACKOFF)\n    core.provider.responses = [ResolutionResult(ResourceState.UNKNOWN, error=error)]\n    transfer = await submit(core)\n    await core.engine.tick()\n    alternate = ParcelProvider("other-parcel")\n    core.registry.register_provider(alternate)\n    core.registry.mark_health(core.provider.descriptor.id, healthy=False)\n    core.now[0] += 1\n    await core.engine.tick()\n    async with database.get_db() as db:\n        attempts = await db.fetchall("SELECT provider_id FROM resolution_attempts ORDER BY rowid")\n    assert [row["provider_id"] for row in attempts] == ["parcel-lab"]\n    assert not [call for call in alternate.calls if call[0] == "resolve"]\n    details = await core.repository.presentation(transfer.id, details=True)\n    assert {item["provider_id"] for item in details["route_attempts"]} == {"parcel-lab"}\n    assert len(await core.repository.active()) == 1\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected one legacy failover test, found {text.count(old)}")
path.write_text(text.replace(old, new, 1))
